### PR TITLE
Propagate exceptions occurring during client instantiation

### LINKED ISSUE #282: ⛓️ Don't break the chain: Propagate caught exceptions
When investigating for https://github.com/andregasser/bigbone/issues/280#issuecomment-1761414760 I noticed that we throw a `BigBoneRequestException` but completely remove any knowledge about prior exceptions that led to this issue.

**Proposal**: We should try to propagate exceptions by always calling the `constructor(message: String, e: Exception)` constructor that allows a root cause to be passed so that the stacktrace contains all necessary information and doesn’t just start with where we threw an exception.

Sometimes, we return `null` in some `catch` statements. Not sure where to start there. I think it could make sense to return non-nullable types instead and throw the exception unless it’s an _expected_ exception (date formatting/parsing or similar for example where it’s okay and almost expected that things can go wrong).

(ℹ️ If proposal is accepted, I’d like to implement this, so feel free to assign me. @andregasser)

### PR DESCRIPTION
**Pull request by PattaFeuFeu**
# Description

This PR improves our error handling when instantiating a `MastodonClient` through the `Builder#build` function.

This closes #282 which was an issue originally created because we found out in #280 that exceptions were just swallowed without doing anything. This resulted in a user of our library not figuring out easily that they were trying to call network code on a main thread.

The main issue in our client instantiation is that we need to get an instance version to know what we’re dealing with. Whether that’s even the case or if we could restructure our code to no longer need that is a different topic which I did not handle here.

I introduced a few new custom Exception classes which are returned in specific cases where we either cannot get server information, a `NodeInfo`’s URL, or an instance version via the API v2 or v1.

I tried to catch only those exceptions that we throw ourselves and not intervene with any more general or other exceptions. This way, I/O exceptions, security exceptions, … should just be propagate uncaught to the caller.

I have kept the double fallback solution for the instance version:

1. Get instance version via `NodeInfoClient`
2. If that fails, get it via the Mastodon API v2
3. If that fails, get it via the Mastodon API v1
4. If that fails, throw an exception that has both the failure of the last Mastodon API call and the initial failure of the `NodeInfoClient` as causes, if possible

# Type of Change

- Bug fix
- Documentation

# Breaking Changes

- `MastodonClient.Builder#build` may now throw a `BigBoneClientInstantiationException`. ~~Java clients will no longer be able to build unless they either surround the build call with a try/catch block or add the exception to the method signature of the function calling the builder.~~ 

# How Has This Been Tested?

I have added new unit tests and tried the “Get public timeline” sample with both existing and non-existing Mastodon servers, with an existing Internet connection and without one.

# Mandatory Checklist

- [x] My change follows the projects coding style
- [x] I ran `gradle check` and there were no errors reported
- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] KDoc added to all public methods

### CODE REVIEW

File: bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt [hunk 1]
```diff
@@ -698,22 +702,50 @@ private constructor(
...
+                try {
+                    getInstanceVersionViaApi()
+                } catch (instanceException: InstanceVersionRetrievalException) {
+                    throw BigBoneClientInstantiationException(
+                        message = "Failed to get instance version of $instanceName",
+                        cause = if (instanceException.cause == instanceException) {
+                            instanceException.initCause(error)
+                        } else {
+                            instanceException
+                        }
```
Comment (PattaFeuFeu) [inline bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt:722]: This part is debatable and could be replaced with just the `instanceException`. I have added the cause to get as detailed a stack trace as possible.

This would be relevant in cases where we fail to get the instance version via server info and then also fail getting it via the API. It would then add the original server info exception as the cause of the `instanceException` we got when attempting to get the version via the Mastodon API.

Users _likely_ won’t be able to do much with the server info exception, so we could potentially remove this.


```suggestion
                        cause = instanceException
```

File: bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt [hunk 2]
```diff
@@ -698,22 +702,50 @@ private constructor(
...
+            )
+        }
+
+        @Throws(InstanceVersionRetrievalException::class)
+        private fun getInstanceVersionViaApi(): String {
+            return try {
+                getInstanceVersionFromApi(2)
+            } catch (e: InstanceVersionRetrievalException) {
+                getInstanceVersionFromApi(1)
+            }
```
Comment (PattaFeuFeu) [inline bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt:748]: If we fail with the v2 version and then also fail with the v1 version, this would only throw the v1 exception to the caller. Adding the v2 exception to the v1 exception is not trivially possible as we likely already set a cause in the exception thrown in `getInstanceVersionFromApi`

**Review by bocops — APPROVED** [review]
Looks good to me. Sections pointed out by you as debatable should work either way for the time being. :)

File: bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt (hunk 1 above)
Comment (PattaFeuFeu) [reply bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt:747]: As soon as we decide that the fallbacks are not worth it, I’m very happy to remove them.

But for the time being, this is likely the way that will get us the most insight (provided library users get in touch with us)

File: bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt (hunk 2 above)
Comment (PattaFeuFeu) [reply bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt:773]: So do you suggest to remove v1 now here or to remove it later once you we officially no longer support v1?

**Comment by andregasser** [comment]
If I could have a quick look at it would be awesome. Will do it today, ok?

File: bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt (hunk 2 above)
Comment (bocops) [reply bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt:773]: I would remove the v1 fallback separately, but consider it to be fine to have the drawback you describe right now.

File: bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt [hunk 3]
```diff
@@ -436,19 +440,20 @@ private constructor(
...
     internal fun performAction(endpoint: String, method: Method, parameters: Parameters? = null) {
-        val response = when (method) {
+        when (method) {
             Method.DELETE -> delete(endpoint, parameters)
             Method.GET -> get(endpoint, parameters)
             Method.PATCH -> patch(endpoint, parameters)
             Method.POST -> post(endpoint, parameters)
             Method.PUT -> put(endpoint, parameters)
-        }
-        response.close()
```
[the remark this answers is not in the document]
Comment (PattaFeuFeu) [reply bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt:449]: I didn’t get rid of it here. 😊 I used [`.use`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html) which automatically closes the resource in the end, yielding the same result for error-free cases, but additionally also making sure we close it if an exception was thrown.

File: bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt (hunk 2 above)
Comment (andregasser) [reply bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt:773]: > Even if we keep the fallback of getting a version via API, we might want to remove the secondary "v1" fallback after all server versions still using it become unsupported at the end of the year. We don't need to make our code more complicated than it already is just some weeks before.

@bocops Where did you get this info from regarding end of year - just curious.

Comment (PattaFeuFeu) [reply bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt:773]: https://github.com/mastodon/mastodon/releases/tag/v3.5.14

> ⚠️ The 3.5.x branch will not receive any update—including security fixes—after 2023-12-31.

Comment (andregasser) [reply bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt:773]: Thanks for the info @PattaFeuFeu . Well then, let's remove the v1 in a separate PR. Fine for me as well. :-)

File: bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt [hunk 4]
```diff
@@ -0,0 +1,47 @@
+package social.bigbone.api.exception
+
+import okhttp3.Response
+import social.bigbone.MastodonClient
+import social.bigbone.nodeinfo.entity.NodeInfo
+
+/**
+ * Exception thrown if we could not instantiate a [MastodonClient]. Mostly used to wrap other more specific exceptions.
+ */
+open class BigBoneClientInstantiationException : Exception {
```
Comment (andregasser) [inline bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt:10]: I might lack some Kotlin knowledge here, but couldn't we inherit from `RuntimeException` instead so that we do not need to explicitly handle or declare exceptions of type `BigBoneClientInstantiationException`? Looking at the modified samples in this PR, I see lots of checked exceptions wrapped in `RuntimeException`.

Comment (PattaFeuFeu) [reply bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt:10]: > Looking at the modified samples in this PR, I see lots of checked exceptions wrapped in `RuntimeException`.

I did that less because I wanted to explicitly wrap it that way. I just wanted to do _something_ that would crash the sample in case we run into that error as I didn’t know which other path we should go with. I didn’t want to wrap the whole sample code (in same cases) in the `try` block.

That I rethrow a `RuntimeException` has no specific reason. 😊 

Extending `RuntimeException` or `IllegalStateException` (which itself extends `RuntimeException`) would still be an option though.

Comment (PattaFeuFeu) [reply bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt:10]: I’ve replaced the try/catch blocks with an extended `throws` clause in the method header like we already did for `BigBoneRequestException` @andregasser

Comment (andregasser) [reply bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt:10]: Hello @PattaFeuFeu Thanks a lot for the changes. Let's assume we let `BigBoneClientInstantiationException` inherit from `RuntimeException` instead of `Exception`. Wouldn't this simplify library user's life as they a) do not need to declare the exception and b) also do not need to catch it if they do not want to?

Comment (bocops) [reply bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt:10]: Kotlin does not have checked exceptions, so wouldn't this would only make a difference in Java? If we want that exception to be unchecked in Java as well, I think we could just remove the `@Throws` annotation - but that seems to be a design decision that we would want to discuss in general, outside of this PR.

For what it's worth, if we discuss the design of our exceptions, we could also talk about naming (which one's get prefixed with "BigBone" and which one's don't?), or whether it makes sense to let all of them inherit from some `BigBoneException` just to group all of them for easier catching.

Comment (andregasser) [reply bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt:10]: Hello @bocops Thanks for the feedback. As you mention, Kotlin does not care about the exception type. But I think it matters for Java devs. I think we could do Java devs a favor if we do not force them to declare/handle exceptions.

Let's say we do this:
- Base all the exceptions we throw on `RuntimeException`
- Remove all the `@Throws` annotations from our methods
- Wrap potential checked exceptions (IOException and such) in RuntimeException before we throw it

Doing so, Java devs should be happy, as they do not explicitly need to handle/declare our exceptions.

Please correct me if I am wrong.

Comment (bocops) [reply bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt:10]: I believe we don't need to change our Exceptions to inherit from RuntimeException explicitly, or wrap other Exceptions, as long as we remove the `@Throws` annotations we currently have in place. That part would definitely be worth discussing, though. :)

Comment (andregasser) [reply bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt:10]: Hello @bocops, Thanks for the example code on Slack, which I quickly repost here for context:

Kotlin code in BigBone:
```kotlin
package social.bigbone.sample

import social.bigbone.api.exception.BigBoneRequestException
import java.io.IOException

class TestThrower {

    @Throws(BigBoneRequestException::class)
    fun throwDeclaredBigBoneException() {
        throw BigBoneRequestException("foo")
    }

    fun throwUndeclaredBigBoneException() {
        throw BigBoneRequestException("foo")
    }

    @Throws(IOException::class)
    fun throwDeclaredJavaException() {
        throw IOException("foo")
    }

    fun throwUndeclaredJavaException() {
        throw IOException("foo")
    }
}
```

Java call site:
image



Based on your results, I suggest, we remove the `@Throws` annotations on all our methods and continue to base our exceptions on simply `Exception` as it clearly works.

Would that be ok for all of you?

Comment (PattaFeuFeu) [reply bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt:10]: > Would that be ok for all of you?

I don’t have a specific opinion on that. But in any case, I would not want to do all of that in this PR. At least not for the other Exceptions that already existed. I could rewrite the new Exceptions added here to not have the `@Throws` declaration (I would still add it to the kDoc though?).

Comment (andregasser) [reply bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt:10]: @PattaFeuFeu Fully agree with you. Thanks for the reply. 👍

Comment (PattaFeuFeu) [reply bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt:10]: I have removed the `@Throws` annotations for _public_ methods but kept them for internal/private ones so that we know what to expect.

I have kept the kDoc `@throws` notes even for the public ones.

File: sample-java/src/main/java/social/bigbone/sample/GetAppRegistration.java [hunk 5]
```diff
@@ -6,19 +6,16 @@
 import social.bigbone.api.exception.BigBoneRequestException;
 
 public class GetAppRegistration {
-    public static void main(final String[] args) {
+    public static void main(final String[] args) throws BigBoneRequestException {
```
[the remark this answers is not in the document]
Comment (PattaFeuFeu) [reply sample-java/src/main/java/social/bigbone/sample/GetAppRegistration.java:9]: Nope, I only removed the `BigBoneInstantiationException` from the client builder. `.execute()` still throws `BigBoneRequestException`. As discussed in the other thread, I won’t remove other exceptions in this PR.

[the remark this answers is not in the document]
Comment (andregasser) [reply sample-java/src/main/java/social/bigbone/sample/GetAppRegistration.java:9]: Ah yes, sorry. Fine for me then.

**Review by andregasser — APPROVED** [review]
👍
